[aws]
style = "dimmed red"
symbol = "🅰 "

[cmd_duration]
format = "~[$duration]($style)"

[directory]
truncate_to_repo = false

[git_branch]
style = "bold green"
symbol = "🅶 "

[git_status]
conflicted = "=$count"
untracked = "?$count"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[nodejs]
style = "bold purple"
symbol = "🅽 "

[ruby]
symbol = "🆁 "

[time]
disabled = false
